---
# Install Samba client packages for mounts

- name: samba mounts | install clients
  become: true
  ansible.builtin.dnf:
    pkg: "{{ item }}"
    state: present
  with_items:
    - samba-client
    - cifs-utils
